### ISSUE TITLE
Update badgeholder manual link

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#24]
"View badgeholder manual" currently links to the R5 manual.

Will ping Jonas for the updated link.

**Comment by meglister** [comment]
Link: https://gov.optimism.io/t/retro-funding-6-badgeholder-manual/9109

cc @vidvidvid

**Comment by vidvidvid** [comment]
thanks, should be deployed to develop branch soon! :) please close the issue once it's deployed
