### ISSUE TITLE
Update images and fonts on ballot page

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#28]
- The images need to be updated to match Figma for each category

- The subtext eg ("Infrastructure and tooling that powered governance or that made the usage of governance infrastructure more accessible.") is 16px in the UI and needs to be changed to 14px to match Figma

**Comment by vidvidvid** [comment]
the subtext is 14px already - can you please check if it was actually 16px on your screen? how large is your screen?

![Screenshot 2024-10-22 at 08 49 44](https://github.com/user-attachments/assets/5b5664c8-0a4c-4631-a064-6f575b81fb73)
