### ISSUE TITLE
Impact statement is missing on project pages

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#39]
Project: https://develop-op-rf-6.up.railway.app/project/0x82783c8ea0cfd3f24730f210996efcc8e64855159e190f2dc430d176021b1733

There is an impact statement that appears here (https://round6.retrolist.app/project/0x432e5f61903ae611d2643ca56fe4e50c573a57bd566161bb323a2ea23072f5f7), which I'm using for a canonical source for the data. However, that impact statement does not appear on-page.

![Screenshot 2024-10-23 at 9 05 09 AM](https://github.com/user-attachments/assets/d71c88c7-80f9-4baa-bf1d-d917e994d08f)
![Screenshot 2024-10-23 at 9 05 05 AM](https://github.com/user-attachments/assets/ce0eca56-47d8-4adf-8ee6-4b6771274545)

**Comment by vidvidvid** [comment]
@meglister please check this as well since i can't view attestations with any of my accounts

**Comment by meglister** [comment]
verified that this is working
