### ISSUE TITLE
Better styling for metricsgarden links

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#40]
The metricsgarden links are styled awkwardly on the site -- could we truncate them and add an icon noting they should open in a new tab?

Link: https://develop-op-rf-6.up.railway.app/project/0xd4120ac98272e4c957b973eaa89459cef30f3762be5d5b2706db160f6a96b445

![Screenshot 2024-10-23 at 9 09 53 AM](https://github.com/user-attachments/assets/0145b1ed-17a3-4f59-a712-5935e670d5e5)

**Comment by shaunop** [comment]
Yes!

1. How about we truncate to 4 digits past projects: "metricsgarden.xyz/projects/0xd4..."
2. Open in a new tab (icon isn't required IMO, we're opening all links to new tabs and not using icons)

**Comment by vidvidvid** [comment]
@shaunop @meglister please check if this has been fixed!

**Comment by shaunop** [comment]
Visual application looks good.
