### ISSUE TITLE
Better styling for no data state

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#41]
Project: https://develop-op-rf-6.up.railway.app/project/0xd4120ac98272e4c957b973eaa89459cef30f3762be5d5b2706db160f6a96b445

This project has no attestations from top delegates. We should have a better null state where there are no attestations (total) or no attestations from either citizens or top delegates.

![Screenshot 2024-10-23 at 9 12 54 AM](https://github.com/user-attachments/assets/23eae389-7354-4218-970a-64a6c5d7a34c)

**Comment by meglister** [comment]
Additionally, some projects have no attestations -- wondering if we should display text noting that? Ex: https://develop-op-rf-6.up.railway.app/project/0x82783c8ea0cfd3f24730f210996efcc8e64855159e190f2dc430d176021b1733

**Comment by meglister** [comment]
Sent this to Shaun for his feedback

**Comment by shaunop** [comment]
If either no delegates or no citizens, how about we disable the tab? (see: Top Delegates is disabled and can't be clicked)  
<img width="737" alt="Screenshot 2024-10-23 at 2 42 07 PM" src="https://github.com/user-attachments/assets/4a96ab51-da9f-4791-a367-87851d18de1c">

If no attestations, how about we try this: 
<img width="734" alt="Screenshot 2024-10-24 at 11 08 55 AM" src="https://github.com/user-attachments/assets/e5192b8f-1c5e-4ffb-a1fb-8b7c7573530c">

**Comment by vidvidvid** [comment]
@meglister @shaunop please check if that has been fixed!

**Comment by geovgy** [comment]
@shaunop should I apply the same to the "attestations from elected governance members" card? Already did the liberty of including it in PR #75 but can change it if you prefer.

This is what it looks like:
![Screenshot 2024-10-25 155346](https://github.com/user-attachments/assets/a2bf66a2-d57c-4f8c-9cd2-785b54c31290)

**Comment by meglister** [comment]
hey @geovgy I am still not seeing the 0 attestations state where I would expect to

Ex: https://develop-op-rf-6.up.railway.app/project/0x176e4151a62d4f67990f90c5d7744afeb1cd4332c11ae00852f9c8af6a5056be

This is in the Governance and Infra tooling category and does not have any attestations. The API call does not have impactMetrics returned at all 
![Screenshot 2024-10-28 at 3 58 27 PM](https://github.com/user-attachments/assets/15792f89-6ec2-4f14-85dc-c7e27b1cd5a5)

Can we show this design for projects that fit that category: 
<img width="734" alt="379887689-e5192b8f-1c5e-4ffb-a1fb-8b7c7573530c" src="https://github.com/user-attachments/assets/962ea5c5-978d-4a32-a767-ff1afa198525">

**Comment by shaunop** [comment]
For the "Attestations from elected gov members" is different from the overall attestations card, in that it's nested under the overall attestations and it's absence communicates that gov officials aren't present. I would simply not show the card if no gov officials had attested.

**Comment by shaunop** [comment]
The "Attestations from elected gov members" is different from the overall attestations card because it's nested under the overall attestations. It's absence communicates that gov officials aren't present. I would simply not show the card if no gov officials had attested to keep the page tight and efficient.

**Comment by geovgy** [comment]
Ok updated. If all looks good, please feel free to close this issue.
