### ISSUE TITLE
Missing contract addresses

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#45]
Looking at this project: https://develop-op-rf-6.up.railway.app/project/0x32e7213faa7fb7919426ae3e3445d47d252677d00a772641c5e4f1626134dd75

Only two contracts are listed in the UI, however many contracts are listed in retrolist: https://round6.retrolist.app/project/0x5decc7c7bb5ac6448be3408fd18e5c75738725d739711985e2c55026d2fa1391

We should be showing all contract addresses available

UI
![Uploading Screenshot 2024-10-23 at 9.23.01 AM.png…]()

Retrolist
![Screenshot 2024-10-23 at 9 24 41 AM](https://github.com/user-attachments/assets/937fb264-dec8-46d7-8873-b5974926ba6e)

**Comment by geovgy** [comment]
Looks like that is because there are only 2 contract addresses returned from the API.

![Screenshot 2024-10-24 005201](https://github.com/user-attachments/assets/8c662bf9-b975-4638-ba96-3565b3ecd43b)

**Comment by meglister** [comment]
ah ok -- then likely will be solved with final data. let's keep this open so i can verify next week

**Comment by stepandel** [comment]
there're only 2 contracts in the attested metadata: https://optimism.easscan.org/attestation/view/0xdef68b0eaf527954764a987d415ba91617006a8c3f9f660ca08f788bfab2fd6e
https://storage.retrofunding.optimism.io/ipfs/QmPw5ecEqgX6nQRFnSjJaLNkV4fpoddf18bu9SN7PU3CPV

so retrolist is likely doing more than just reading the attestations -- I can see they have some contracts duplicated. Also I see proxies and implementations being both referenced. (we are only using attestations metadata as SOT)

**Comment by vidvidvid** [comment]
@stepandel any way we could pull in more data, like retrolist?

**Comment by stepandel** [comment]
this is not something we're planning on doing -- will be using attestations as a SOT
