### ISSUE TITLE
Issue saving custom allocations in ballot

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#46]
When I try to edit my custom allocations on the ballot, I get an "error saving ballot" message. It also seems like that action logs me out? I don't totally understand what's going on here or what's triggering it -- please see the loom below!

https://www.loom.com/share/31f34f3050b44764874754d5e3245795

**Comment by vidvidvid** [comment]
@meglister is this ongoing?

**Comment by meglister** [comment]
@vidvidvid Still happening, figured out repro steps:
1. Log in, allocate budget, rate projects
2. Assign one allocation method (eg impact groups) then switch to custom
3. Make one edit in the custom method, observe it succeeds
4. Make another edit, observe it produces an error and 401 responses from the API

Video: https://www.loom.com/share/eed0f773fd734a988b57153ea2686b52

**Comment by vidvidvid** [comment]
@meglister could you do the same as in the other video and inspect the tabs of the network tab?

**Comment by meglister** [comment]
@vidvidvid can no longer repro this, will close
