### ISSUE TITLE
Error resetting ballot

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#47]
When I click the button to reset my ballot, I am prompted with a confirmation modal. Before I have the chance to click "reset ballot" on the modal, I get an "error resetting ballot" toast in the bottom right of the screen. There is also a console error. Screenshot attached.

![Screenshot 2024-10-23 at 9 40 05 AM](https://github.com/user-attachments/assets/d77309f4-40f9-461e-a5cb-4d5efa022bd6)

**Comment by geovgy** [comment]
Unable to replicate. Possibly an API issue that has since been fixed?

**Comment by meglister** [comment]
@geovgy this is still happening to me: https://www.loom.com/share/1de49700ddd54412851b29a396b02f33

I will also report to agora

**Comment by meglister** [comment]
https://github.com/voteagora/agora-next/issues/575

**Comment by meglister** [comment]
I was able to reset my ballot using a different wallet and voting category! So weird. Here's a video of that experience and then I immediately tried with the problem wallet/category and got the same error: https://www.loom.com/share/a638cc87a0234ed0bca4eb61914cfc74?sid=ff0e095d-55be-461a-97d3-432eedc0dabd

**Comment by stepandel** [comment]
tried resetting the ballot -- works for me.
the API call that you're making to `rounds/6/ballots/{address}/projects` will error if it does not include the full ballot of projects (no more, no less)
As I can't repro, my best guess at what could've happened is that the provided list of projects was missing some projects

**Comment by vidvidvid** [comment]
@meglister are you still unable to reset the ballot with your original wallet/category? i can see 142 projects getting logged in your console - isn't this 2x the amount of gov infra? there might be something fishy going on in the formation of the payload.

**Comment by meglister** [comment]
yes, this is still happening to me @vidvidvid

**Comment by meglister** [comment]
here is the recording! https://www.loom.com/share/09112182ff96475aa334c0561e56e6e7

**Comment by vidvidvid** [comment]
aha, you're getting 'invalid projects for voter category' error! no clue how that could have happend... @geovgy got any idea about that?

**Comment by geovgy** [comment]
@meglister I think there might be an issue with your particular ballot. Possibly some projects in your `project_allocations` list that aren't supposed to be in there. We only reset the allocations from that list. Reference [here](https://github.com/grants-stack-frontier/op-rf-6/blob/fa7f576c2fdecd73c4f92c818b536d0fa961c784/src/components/metrics-editor/reset-button.tsx#L32):
```typescript=
const handleReset = async () => {
    if (!ballot?.project_allocations || !address) return;
    await saveProjects({
      projects: ballot.project_allocations.map((project) => ({
        project_id: project.project_id,
        allocation: '0',
        impact: project.impact as ImpactScore,
      })),
      action: 'reset',
    });

    resetDistributionMethod();

    queryClient.invalidateQueries({ queryKey: ['ballot-round5', address] });

    setIsOpen(false);
  };
```

**Comment by stepandel** [comment]
I've reset your project allocations in the ballot @meglister. It's likely that once we switched to new R6 attestations your allocaiton gorup has changed.

**Comment by vidvidvid** [comment]
@meglister did this solve your problem?
@stepandel would it make sense to reset all the project allocations?

**Comment by meglister** [comment]
Aha, this did solve my problem, thanks both!

**Comment by vidvidvid** [comment]
awesome!! :D
