### ISSUE TITLE
Error submitting ballot

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#49]
When I submit my ballot, I am correctly prompted with the survey and to sign a message which contains the correct allocations. However, after I sign the message my ballot submission fails. See screenshot for console error

![Screenshot 2024-10-23 at 9 43 34 AM](https://github.com/user-attachments/assets/b1bf747e-4a65-4a82-ac9c-3c2a92105f8e)

**Comment by meglister** [comment]
Recorded a video and will also submit to agora: https://www.loom.com/share/8387448b5f5d497aa500ae1ba89ba69f

**Comment by meglister** [comment]
xposted here - https://github.com/voteagora/agora-next/issues/576

**Comment by stepandel** [comment]
submission bug in the API has been fixed -- please reopen issue on Agora if ballot submission is still not working for you

**Comment by vidvidvid** [comment]
closing the issue in favour of the agora fix
