### ISSUE TITLE
Ensure attestations comparison is hooked up to API

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#51]
There is comparison text in the number of attestations box on project pages that reads "More than most other Governance Infrastructure & Tooling projects."

Can you please verify that this is hooked up to the API and is dynamic per project? I am only finding projects that read "more than" vs "less than" or "equal to." I don't have a real way to verify that it is correct, though I've done the math on the OSO data export to find that that average number of attestations = 3. By that math, this project should likely read "less than": https://develop-op-rf-6.up.railway.app/project/0xd4120ac98272e4c957b973eaa89459cef30f3762be5d5b2706db160f6a96b445

<img width="372" alt="Screenshot 2024-10-23 at 7 44 29 PM" src="https://github.com/user-attachments/assets/e2f3b01c-02d9-4411-920e-bc96346e8333">

**Comment by vidvidvid** [comment]
@meglister i can't see any attestations at all, could you check if this has been resolved for you?

**Comment by meglister** [comment]
Hey @vidvidvid , I still see the same behavior

Looking at this project: https://develop-op-rf-6.up.railway.app/project/0xd4120ac98272e4c957b973eaa89459cef30f3762be5d5b2706db160f6a96b445

There are 2 attestations and it reads "more than most"
![Screenshot 2024-10-24 at 9 50 39 AM](https://github.com/user-attachments/assets/5b7049ec-c9a5-43df-8af8-dd8e26561531)

**Comment by vidvidvid** [comment]
@geovgy

**Comment by geovgy** [comment]
In the app, I calculate the average number of attestations per project in the gov infra category and the text says "more than" or "less than" based on whether the number of attestations for that project is greater/less than the average. Oddly, the average is under 1 (~0.92) which explains the above behavior.

**Comment by shaunop** [comment]
Interesting. Given the small number of attestations, let's remove this text entirely. Here's the ask:

1. Please remove the "more than / less than" line
2. Let's please adjust the copy to say "Top 100 Delegates" and remove the * and remove the sub-line "*The top 100 delegates by voting power"

<img width="367" alt="Screenshot 2024-10-25 at 11 39 51 AM" src="https://github.com/user-attachments/assets/b82e8cd6-428d-4fc7-9883-cfad426ed70e">

**Comment by meglister** [comment]
@geovgy just talked to @shaunop , let's remove this text entirely. 

Keep: By Citizens / Delegates (and asterisk text)
Remove: More than / Less than most other Governance & Infrastructure tooling projects

**Comment by geovgy** [comment]
Ok. I opened it as a new issue and will close this one now.
