### ISSUE TITLE
New Voting form

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#54]
You can find the DeForm for the voter survey [here](https://app.deform.cc/form/a15a5008-314a-4323-85c5-fe0ee0939004)
Form ID: a15a5008-314a-4323-85c5-fe0ee0939004
The questions have not changed, so everything should remain the same. Once you have it implemented, I can check that responses are send correctly

**Comment by geovgy** [comment]
@JSeiferth the figma includes a few new questions which I have already implemented (minus the form ids to actually work). Should I revert back to the questions in this survey then?

**Comment by geovgy** [comment]
Nevermind, I see the questions in the survey has now been updated. Thanks!

**Comment by geovgy** [comment]
@JSeiferth you should see at least 2 response submissions from testing. Please confirm you got them.

**Comment by meglister** [comment]
Jonas confirmed over slack, we can close this @geovgy
