### ISSUE TITLE
Attestations from Gov Official: NPS Score easily confused for Count not Rating

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf-6#57]
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/project/0x183766e346b3d36aa8586f3aa6260f7bd8c2d232e1e68f3ecf44e8ec1ab25a6c

### What happened?

The page is as designed. On review, it feels to me like the NPS score will easily be confused as a person count, and not the NPS score. 

### What should have happened instead?

Can we please update this module and append "...out of 10" to the NPS scores, like this: 
<img width="730" alt="Screenshot 2024-10-24 at 11 13 27 AM" src="https://github.com/user-attachments/assets/60a88ac5-d7cb-4da8-ac49-2a1433f65b50">

### Steps to Reproduce

.

**Comment by vidvidvid** [comment]
@shaunop please check if this has been resolved. if yes, please close the issue.
