### ISSUE TITLE
Getting a 404 when I click to "View all testimonials at metricsgarden.xyz/projects/0x1a..."

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf-6#70]
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/project/0x1a34881e1e66e3e9ef20d1d441ce2ef984adf05a25ce8ccae0e483d837249990

### What happened?

When I click the link to "View all testimonials at metricsgarden.xyz/projects/0x1a...", I get directed to a 404.

### What should have happened instead?

I should land on that project's Metrics Garden page (ex: https://www.metricsgarden.xyz/projects/0x5e6c436e48e56d6d9622ba5d0be0035c314e2b29d2afc8f5f1ee8ac75cd42532/?tab=insights)

### Steps to Reproduce

-

**Comment by meglister** [comment]
Pretty sure this is a bug on the Metrics Garden end! Will report to them

**Comment by geovgy** [comment]
Nope @meglister its my bad. Just fixed it and will merge soon.

**Comment by meglister** [comment]
oh nice thanks @geovgy !
