### ISSUE TITLE
Direct "View all testimonials at metricsgarden.xyz/projects/0x1a..." link to Insights Tab on Metrics Garden page

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf-6#71]
### What was the URL where the error occurred?

https://www.metricsgarden.xyz/projects/0x5e6c436e48e56d6d9622ba5d0be0035c314e2b29d2afc8f5f1ee8ac75cd42532/?tab=insights

### What happened?

Currently, the "View all testimonials" link directs to the project's "contributions" tab on Metrics Garden. Let's direct straight to the ["Insights" tab](https://www.metricsgarden.xyz/projects/0x5e6c436e48e56d6d9622ba5d0be0035c314e2b29d2afc8f5f1ee8ac75cd42532/?tab=insights) if possible. That's where the attestations from individuals are hosted.

### What should have happened instead?

NA

### Steps to Reproduce

NA

**Comment by geovgy** [comment]
Included in my fix for #70
