### ISSUE TITLE
round6.optimism.io not working

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#81]
### What was the URL where the error occurred?

round6.optimism.io

### What happened?

When landing, I see this
<img width="1512" alt="Screenshot 2024-10-29 at 08 57 52" src="https://github.com/user-attachments/assets/66fb7d99-bd76-454b-8cfb-80d9f821d4b3">

### What should have happened instead?

-

### Steps to Reproduce

-

**Comment by vidvidvid** [comment]
@JSeiferth  this is intentional. give a sign and we'll go live!
