### ISSUE TITLE
Add Pareto allocation method to the ballot

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf-6#82]
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/

### What happened?

Please add an allocation method to the ballot. The method is called "Pareto distribution". Add an allocation card to the left of custom. On hover, please show this text:

> The Pareto distribution is a power law probability distribution which states that 80% of outcomes are due to 20% of causes. Alse known as the “80-20 rule”.

<img width="1084" alt="Screenshot 2024-10-29 at 4 07 17 PM" src="https://github.com/user-attachments/assets/1e03f9df-745d-4c82-9ef7-3313c8df0779">
---

<img width="1088" alt="Screenshot 2024-10-29 at 4 07 27 PM" src="https://github.com/user-attachments/assets/8f863b9b-a52c-4aeb-b20b-674b38d16f9e">

**[Figma](https://www.figma.com/design/1j0mOMlZWtve4GK5kF0WQU?node-id=9432-92338#1005737968)** 

### What should have happened instead?

NA

### Steps to Reproduce

NA

**Comment by geovgy** [comment]
@shaunop I accidentally left out distribution in "Pareto distribution" and wondering if it looks better that way. If not, I can quickly patch that.

**Comment by meglister** [comment]
hey @geovgy since OP is at a retreat they're probably slow to respond. let's just patch it to match designs! thank you

**Comment by geovgy** [comment]
Ok updated for now and will keep this issue open for thoughts

**Comment by vidvidvid** [comment]
closing this issue for cleaning purposes - will reopen if we get any complaints
