### ISSUE TITLE
Details for pricing model missing

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#85]
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/project/0x59718022161d39195c341d8c9a36f744c9070f73e0ba8d52553d594380aa8460

### What happened?

I would expect to see more details & supporting text for the freemium model.

Figma mockups:
![Screenshot 2024-10-30 at 9 22 15 AM](https://github.com/user-attachments/assets/26a7696b-57e8-44a3-acfc-fa34f951b947)

JSON of project data attached to show "pricingModelDetails": "DeepDAO is about to start selling subscriptions to Pro DAO dashboards. The cost will be 3k-5k a month. The Optimism Pro version is available to the community for free. DeepDAO also sells data API for academics and research institutes. "
[applications.json](https://github.com/user-attachments/files/17573413/applications.json)

Noting that I do not see a pricingModelDetails field in the API -- we may need to flag this with Agora
![Screenshot 2024-10-30 at 9 23 26 AM](https://github.com/user-attachments/assets/7a843fb8-2e70-4ee7-a798-c2c7a54b25b8)

### What should have happened instead?

see above

### Steps to Reproduce

see above

**Comment by meglister** [comment]
@geovgy should I escalate with Stepan?

**Comment by stepandel** [comment]
just added `pricingModelDetails` as a separate attribute
