### ISSUE TITLE
Allocations not adding up to 100%

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#88]
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/ballot

### What happened?

When selecting the "impact group" method, the allocation doesn't add up to 100%

<img width="672" alt="Screenshot 2024-10-30 at 09 37 29" src="https://github.com/user-attachments/assets/29e40669-b39d-418e-b56a-329cb27b7ed4">

### What should have happened instead?

When selecting the "impact group" method, the projects should add up to 100%

### Steps to Reproduce

1. Rate projects from very low to very high
2. Apply Impact group allocation method

**Comment by vidvidvid** [comment]
this was brought to stepan's attention

**Comment by vidvidvid** [comment]
@JSeiferth this doesn't happen to me anymore. can you check the status of this and close the issue it if it's working?

**Comment by geovgy** [comment]
This has been resolved on the API side.
