### ISSUE TITLE
CSV Export has 0s for allocation

### ISSUE THREAD

**Issue by meglister** [grants-stack-frontier/op-rf-6#90]
When I export my ballot, I expect to see a % in the allocation column that reflects the UI. However, when I download my ballot, the allocation column is all 0s.

See CSV attached
[ballot_template (2).csv](https://github.com/user-attachments/files/17578842/ballot_template.2.csv)

**Comment by geovgy** [comment]
Can you provide steps or a recording of reproducing it? If its a mismatch between the UI and CSV amounts, I'm struggling to get that state. But I do see null values in your CSV which could mean an issue in the API

**Comment by meglister** [comment]
i'm not able to repro this anymore either -- maybe it was a transient issue!

**Comment by vidvidvid** [comment]
closing until it (hopefully not) appears again
