### ISSUE TITLE
Ballot submission error

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#94]
### What was the URL where the error occurred?

https://round6.optimism.io/ballot

### What happened?

I'm on a random wallet and want to submit my ballot. I get an error 
<img width="1481" alt="Screenshot 2024-10-31 at 16 23 35" src="https://github.com/user-attachments/assets/ef7b6ce3-e5b6-45e8-bf78-1c21f31accd2">

### What should have happened instead?

-

### Steps to Reproduce

-

**Comment by meglister** [comment]
@vidvidvid we can close -- this was an API issue resolved by Stepan
