### ISSUE TITLE
Testimonials: chart numbers

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#95]
### What was the URL where the error occurred?

https://round6.optimism.io/project/0x26d1186a0d4350e5b6c362372cacf08b29963e305f5ac08ce48e27eaadc4f8cc

### What happened?

<img width="757" alt="Screenshot 2024-10-31 at 16 55 47" src="https://github.com/user-attachments/assets/4d5d60af-abb6-4e6c-ab34-93fd8fe22056">

The chart number when hovering over the pie slice is displayed as 0.5, it should be displayed as 50%

### What should have happened instead?

-

### Steps to Reproduce

-

**Comment by vidvidvid** [comment]
fixed!
