### ISSUE TITLE
Testimonials: elected governance members PMF question

### ISSUE THREAD

**Issue by JSeiferth** [grants-stack-frontier/op-rf-6#96]
### What was the URL where the error occurred?

https://round6.optimism.io/project/0xebf5613bac605b69e6665ee526b00d31c1d440ae2424266fa1be5847f5d0c24b

### What happened?

When looking at the [Curia application](https://round6.optimism.io/project/0xebf5613bac605b69e6665ee526b00d31c1d440ae2424266fa1be5847f5d0c24b), looking at "elected governance members" section, and seeing the statement next to the average score, where it says "Neutral if ceased to exist" - it should say "extremely upset if ceased to exist instead". 
<img width="1512" alt="Screenshot 2024-11-02 at 10 56 02" src="https://github.com/user-attachments/assets/e3b4743c-00a8-43ae-9d57-4e30666a4dda">

### What should have happened instead?

The scores on the API are interpreted incorrectly. How it should work
avg_pmf_score  >= 2.5  -  Extremely upset
avg_pmf_score  1.5 - 2.5 - Somewhat upset
avg_pmf_score < 1.5 -  Neutral

This issue applies to all applications

### Steps to Reproduce

1. Go to [Curia Application](https://round6.optimism.io/project/0xebf5613bac605b69e6665ee526b00d31c1d440ae2424266fa1be5847f5d0c24b)
2. See "Neutral if ceased to exist"

**Comment by vidvidvid** [comment]
@JSeiferth should be resolved now. please close the issue once confirmed
